### ISSUE TITLE
add hover effects to navbar and making it responsive

### ISSUE THREAD

**Issue by Janhvi52** [Riya14-dangra/COFFEE-SHOP#7]
can you assign me this issue?

**Comment by Riya14-dangra** [comment]
> can you assign me this issue?

first complete the previous one then i will assign this to you

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Riya14-dangra , can u assign me this issue ?

**Comment by himanshu1221** [comment]
can u please assign this issue to me under KWoC22

**Comment by Riya14-dangra** [comment]
> can you assign me this issue?

@Janhvi52 will you wish to work on this issue or I will assign it to someone else

**Comment by Janhvi52** [comment]
> > can you assign me this issue?
> 
> @Janhvi52 will you wish to work on this issue or I will assign it to someone else

Since I've mentioned it first, I would like to work on the issue

**Comment by Riya14-dangra** [comment]
> > > can you assign me this issue?
> > 
> > 
> > @Janhvi52 will you wish to work on this issue or I will assign it to someone else
> 
> Since I've mentioned it first, I would like to work on the issue

Okay @Janhvi52 go for it

**Comment by Riya14-dangra** [comment]
@himanshu1221 & @DHRUVKHANDELWAL00  create a new issue and start working on it

**Comment by himanshu1221** [comment]
okay @Riya14-dangra

**Comment by SattyamSamania** [comment]
Hey @Riya14-dangra if the issue is not solved can I work on this?

**Comment by Riya14-dangra** [comment]
> Hey @Riya14-dangra if the issue is not solved can I work on this?

No @Janhvi52 is working on this you go for another one

**Comment by SattyamSamania** [comment]
> > Hey @Riya14-dangra if the issue is not solved can I work on this?
> 
> No @Janhvi52 is working on this you go for another one

Hey @Riya14-dangra Can I start working now?

**Comment by Riya14-dangra** [comment]
@Janhvi52 you can start working on it give me the status of your work within one day
